version: '3'

networks:
  laravel1:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx1
    ports:
      - 81:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php1
      - mysql1
    networks:
      - laravel1

  mysql1:
    image: mariadb:10.6
    container_name: mysql1
    restart: unless-stopped
    tty: true
    ports:
      - 3301:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql1
    networks:
      - laravel1

  php1:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php1
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel1

  composer1:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer1
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php1
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel1

  npm1:
    image: node:13.7
    container_name: npm1
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel1

  artisan1:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan1
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql1
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel1